export const UPDATE_FIRST_NAME = 'UPDATE_FIRST_NAME';
export const UPDATE_LAST_NAME = 'UPDATE_LAST_NAME';
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';
export const UPDATE_CITY = 'UPDATE_CITY';
export const UPDATE_STATE = 'UPDATE_STATE';
export const UPDATE_ZIPCODE = 'UPDATE_ZIPCODE';
export const UPDATE_SHIPPING_OPTION_ID = 'UPDATE_SHIPPING_OPTION_ID';
