export const REGISTER_ACCOUNT = 'REGISTER_ACCOUNT';
export const STORE_USER = 'STORE_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const SELECT_CATEGORY = 'SELECT_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const SELECT_DEPARTMENT = 'SELECT_DEPARTMENT';
export const CLEAR_DEPARTMENT = 'CLEAR_DEPARTMENT';
