export const INCREMENT_ITEM_IN_CART = 'INCREMENT_ITEM_IN_CART';
export const DECREMENT_ITEM_IN_CART = 'DECREMENT_ITEM_IN_CART';
export const UPDATE_ITEM_AMOUNT_IN_CART = 'UPDATE_ITEM_AMOUNT_IN_CART';
export const ADD_ITEMS_TO_CART = 'ADD_ITEMS_TO_CART';
